### PR TITLE
feat: monitoring

### PR DESCRIPTION
**Pull request by HilkopterBob**
This PR adds `/metrics` which exports: requests, requests in progress and requests per status code

closes: #105 

example from dev environment:
```go
# HELP http_request_duration_seconds Duration of all HTTP requests by status code, method and path.
# TYPE http_request_duration_seconds histogram
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="1e-09"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="2e-09"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="5e-09"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="1e-08"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="2e-08"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="5e-08"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="1e-07"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="2e-07"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="5e-07"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="1e-06"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="2e-06"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="5e-06"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="1e-05"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="2e-05"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="5e-05"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="0.0001"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="0.0002"} 0
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="0.0005"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="0.001"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="0.002"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="0.005"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="0.01"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="0.02"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="0.05"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="0.1"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="0.2"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="0.5"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="1"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="2"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="5"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="10"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="15"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="20"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="30"} 1
http_request_duration_seconds_bucket{method="GET",path="/",service="PackageLock",status_code="404",le="+Inf"} 1
http_request_duration_seconds_sum{method="GET",path="/",service="PackageLock",status_code="404"} 0.000328517
http_request_duration_seconds_count{method="GET",path="/",service="PackageLock",status_code="404"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="1e-09"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="2e-09"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="5e-09"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="1e-08"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="2e-08"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="5e-08"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="1e-07"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="2e-07"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="5e-07"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="1e-06"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="2e-06"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="5e-06"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="1e-05"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="2e-05"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="5e-05"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="0.0001"} 0
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="0.0002"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="0.0005"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="0.001"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="0.002"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="0.005"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="0.01"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="0.02"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="0.05"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="0.1"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="0.2"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="0.5"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="1"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="2"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="5"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="10"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="15"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="20"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="30"} 1
http_request_duration_seconds_bucket{method="GET",path="/auth/login",service="PackageLock",status_code="404",le="+Inf"} 1
http_request_duration_seconds_sum{method="GET",path="/auth/login",service="PackageLock",status_code="404"} 0.00014844
http_request_duration_seconds_count{method="GET",path="/auth/login",service="PackageLock",status_code="404"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="1e-09"} 0
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="2e-09"} 0
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="5e-09"} 0
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="1e-08"} 0
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="2e-08"} 0
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="5e-08"} 0
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="1e-07"} 0
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="2e-07"} 0
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="5e-07"} 0
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="1e-06"} 0
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="2e-06"} 0
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="5e-06"} 0
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="1e-05"} 0
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="2e-05"} 0
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="5e-05"} 0
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="0.0001"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="0.0002"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="0.0005"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="0.001"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="0.002"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="0.005"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="0.01"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="0.02"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="0.05"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="0.1"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="0.2"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="0.5"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="1"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="2"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="5"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="10"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="15"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="20"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="30"} 1
http_request_duration_seconds_bucket{method="GET",path="/favicon.ico",service="PackageLock",status_code="404",le="+Inf"} 1
http_request_duration_seconds_sum{method="GET",path="/favicon.ico",service="PackageLock",status_code="404"} 7.2866e-05
http_request_duration_seconds_count{method="GET",path="/favicon.ico",service="PackageLock",status_code="404"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="1e-09"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="2e-09"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="5e-09"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="1e-08"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="2e-08"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="5e-08"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="1e-07"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="2e-07"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="5e-07"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="1e-06"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="2e-06"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="5e-06"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="1e-05"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="2e-05"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="5e-05"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="0.0001"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="0.0002"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="0.0005"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="0.001"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="0.002"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="0.005"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="0.01"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="0.02"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="0.05"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="0.1"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="0.2"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="0.5"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="1"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="2"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="5"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="10"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="15"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="20"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="30"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404",le="+Inf"} 1
http_request_duration_seconds_sum{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404"} 0.000107192
http_request_duration_seconds_count{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404"} 1
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="1e-09"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="2e-09"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="5e-09"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="1e-08"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="2e-08"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="5e-08"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="1e-07"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="2e-07"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="5e-07"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="1e-06"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="2e-06"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="5e-06"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="1e-05"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="2e-05"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="5e-05"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="0.0001"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="0.0002"} 0
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="0.0005"} 2
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="0.001"} 10
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="0.002"} 10
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="0.005"} 11
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="0.01"} 11
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="0.02"} 11
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="0.05"} 11
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="0.1"} 11
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="0.2"} 11
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="0.5"} 11
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="1"} 11
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="2"} 11
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="5"} 11
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="10"} 11
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="15"} 11
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="20"} 11
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="30"} 11
http_request_duration_seconds_bucket{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200",le="+Inf"} 11
http_request_duration_seconds_sum{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200"} 0.008391442
http_request_duration_seconds_count{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200"} 11
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="1e-09"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="2e-09"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="5e-09"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="1e-08"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="2e-08"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="5e-08"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="1e-07"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="2e-07"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="5e-07"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="1e-06"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="2e-06"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="5e-06"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="1e-05"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="2e-05"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="5e-05"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="0.0001"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="0.0002"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="0.0005"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="0.001"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="0.002"} 0
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="0.005"} 1
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="0.01"} 1
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="0.02"} 1
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="0.05"} 1
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="0.1"} 1
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="0.2"} 1
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="0.5"} 1
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="1"} 1
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="2"} 1
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="5"} 1
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="10"} 1
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="15"} 1
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="20"} 1
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="30"} 1
http_request_duration_seconds_bucket{method="POST",path="/auth/login",service="PackageLock",status_code="401",le="+Inf"} 1
http_request_duration_seconds_sum{method="POST",path="/auth/login",service="PackageLock",status_code="401"} 0.002502502
http_request_duration_seconds_count{method="POST",path="/auth/login",service="PackageLock",status_code="401"} 1
# HELP http_requests_in_progress_total All the requests in progress
# TYPE http_requests_in_progress_total gauge
http_requests_in_progress_total{method="GET",service="PackageLock"} 0
http_requests_in_progress_total{method="POST",service="PackageLock"} 0
# HELP http_requests_total Count all http requests by status code, method and path.
# TYPE http_requests_total counter
http_requests_total{method="GET",path="/",service="PackageLock",status_code="404"} 1
http_requests_total{method="GET",path="/auth/login",service="PackageLock",status_code="404"} 1
http_requests_total{method="GET",path="/favicon.ico",service="PackageLock",status_code="404"} 1
http_requests_total{method="GET",path="/v1/auth/login",service="PackageLock",status_code="404"} 1
http_requests_total{method="GET",path="/v1/general/agents",service="PackageLock",status_code="200"} 11
http_requests_total{method="POST",path="/auth/login",service="PackageLock",status_code="401"} 1

```

### CODE REVIEW

**Comment by HilkopterBob** [comment]
We can add custom metrics to. But i dont think there are any right now. What do you think @Kartoffel096 ?

**Comment by HilkopterBob** [comment]
i also bumped our dependencies, forgot to mention

**Comment by Kartoffel096** [comment]
> We can add custom metrics to. But i dont think there are any right now. What do you think @Kartoffel096 ?

We can prepare some like "agents online", "agents registered", "failed register attempts", "count of how many updates are missing", "count of new updates in the last 24h Hours", etc. etc.

**Review by Kartoffel096 — APPROVED** [review]

**Comment by HilkopterBob** [comment]
i will look into the custom metrics. i am thinkig about:
- registered agents
- registered hosts
- count of different linux distros
- count of different packages
---
As we currently do net have the functionality to check for outdated packages, i hesitate implementing functions like "pending updates" as i do not want to introduce dead, non-functioning code into the code base this early on

**Comment by HilkopterBob** [comment]
this will have to wait until the upstream dependency [Fiber-Prometheus](https://github.com/ansrivas/fiberprometheus) is fully migrated to gofiber/contrib

**Pull request merged**
